Update CMakeLists.txt
/usr/local/include/QtCore/qcompilerdetection.h:1259:6: error: "Qt requires a C++17 compiler"
#    error "Qt requires a C++17 compiler" :
        set(CMAKE_CXX_STANDARD 17)
        set(CMAKE_CXX_STANDARD_REQUIRED ON)